version: "3.2"
services:
  kali:
    container_name: kali
    build:
      context: .
      dockerfile: docker/kali/Dockerfile
    #restart: always
    #command: sleep infinity
    command: sleep infinity
  d-workers:
    container_name: d-workers
    build:
      context: .
      dockerfile: docker/d-scraper/Dockerfile
    volumes:
      - volume_server:/usr/src/workersapp
    depends_on:
      - d-redis
      - d-rabbitmq
    environment:
      - REDIS_HOST=d-redis
      - RABBITMQ_HOST=d-rabbitmq
      - POSTGRES_DB=dailytopic
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=d-postgres
      - POSTGRES_PORT=5432
    #restart: always
    #command: sleep infinity
    command: celery -A workers worker -l debug
  redis:
    image: redis:alpine
    hostname: d-redis
    ports:
        - "6378:6379"
    volumes:
        - ~/.docker-conf/redis/data/:/data
        - ~/.docker-conf/redis/log/:/logs

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
        - "5673:5672"
        - "15673:15672"
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

volumes:
  # volume_proxyengine:
  #   driver: local
  #   driver_opts:
  #     o: bind
  #     type: none
  #     device: /Users/beyond/dailyTopic/proxyengine
  volume_server:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/beyond/pentester